version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          memory: 150M